### ISSUE TITLE
Game Crashing Due to Items

### ISSUE THREAD

**Issue by Felipefpl** [EthanReed517/XML2-Ultimate-Patch#24]
This can occur if your stash and inventory is full or near full. This was reported in the site below and i didnt see any mention of this being fixed:

https://www.pcgamingwiki.com/wiki/X-Men_Legends_II:_Rise_of_Apocalypse

**Comment by EthanReed517** [comment]
This is not within our capability to fix, as it's hard-coded within the game's exe. The only way to address it is through user inventory management.
