### ISSUE TITLE
Game not Starting after Installation

### ISSUE THREAD

**Issue by Felipefpl** [EthanReed517/XML2-Ultimate-Patch#25]
On some newer systems, due to a possible error in the Registry during Installation, the game does not launch or simply crashes on launch. This was reported in the site below:

https://www.pcgamingwiki.com/wiki/X-Men_Legends_II:_Rise_of_Apocalypse

**Comment by EthanReed517** [comment]
This is already addressed in the [XML2 Mod Installation Guide](https://marvelmods.com/forum/index.php/topic,11322.0.html) through an external tool. It's not within our capabilities to fix at the source.
